SELECT P.PRODUCT_CODE, P.PRICE * T.SALES_AMOUNT AS SALES
FROM PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS T ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;
