SELECT ID,
CASE WHEN PERCENTAGE <= 0.25 THEN 'CRITICAL'
WHEN PERCENTAGE <= 0.5 THEN 'HIGH'
WHEN PERCENTAGE <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM (
    SELECT *, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENTAGE
    FROM ECOLI_DATA
) AS T
ORDER BY ID;