WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, P.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS E
    JOIN ECOLI_GEN AS P
    ON E.PARENT_ID = P.ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM ECOLI_GEN AS G
LEFT JOIN ECOLI_DATA AS E
ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;