SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * T.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
) AS T ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;