SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS T ON F.FLAVOR = T.FLAVOR
ORDER BY F.TOTAL_ORDER + T.TOTAL_ORDER DESC
LIMIT 3;