SELECT P.MEMBER_NAME, T.REVIEW_TEXT, T.REVIEW_DATE
FROM MEMBER_PROFILE AS P
JOIN (    
    SELECT MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (    
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(*) = (
            SELECT COUNT(*)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1
        )
    )
) AS T ON P.MEMBER_ID = T.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;