SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, T.MAX_SIZE - D.SIZE_OF_COLONY AS YEAR_DEV, D.ID
FROM ECOLI_DATA AS D
    JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR) AS T 
ON YEAR(D.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, YEAR_DEV;